version: "3"

networks:
  backend_drivenops:
    driver: bridge

volumes:
  pg_drivenops:
  react_drivenops:

services:
  db_postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 4457:5432
    networks:
      - backend_drivenops
    env_file:
      - back-end/.env
    volumes:
      - pg_drivenops:/var/lib/postgresql/data

  node_drivenops:
    container_name: node_drivenops
    build: back-end
    ports:
      - 5000:5000
    depends_on:
      - db_postgres
    networks:
      - backend_drivenops
    env_file:
      - back-end/.env

  app_react:
    build: front-end
    container_name: app_react_drivenops
    networks:
      - backend_drivenops
    volumes:
      - react_drivenops:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx_drivenops
    ports:
      - 80:80
    networks:
      - backend-drivenops
    volumes:
      - react_drivenops:/var/www/html
    depends_on:
      - app_react
      - node_drivenops
